### ISSUE TITLE
Cache apt-packages of dockers

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_travis#128]
We can use apt-cacher-ng to speedup apt-get.

https://docs.docker.com/examples/apt-cacher-ng/

**Comment by k-okada** [comment]
on docker@jenkins, we use custom ros docker image (ros-ubuntu:{12.04,14.04}
that already installed most of ros packages.
 https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis_jenkins.py#L97

--
◉ Kei Okada

**Comment by garaemon** [comment]
great, is it different from ros official docker images?

**Comment by garaemon** [comment]
cf. https://hub.docker.com/_/ros/

**Comment by k-okada** [comment]
yes, we'd use official one at some point.

--
◉ Kei Okada

**Comment by k-okada** [comment]
オフィシャルのdocker imageは release で shadow-fixed ではないですね．

--
◉ Kei Okada
