### ISSUE TITLE
Colorize jenkins output

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_travis#13]
http://srz-zumix.blogspot.jp/2012/04/jenkins-google-test.html

**Comment by garaemon** [comment]
Added

![_009](https://cloud.githubusercontent.com/assets/40454/5892784/b1632e28-a50e-11e4-89f6-2da35a903096.png)

**Comment by garaemon** [comment]
now jenkins generates new projects for each travis job and output from jenkins gets ugly again

**Comment by k-okada** [comment]
done https://github.com/jsk-ros-pkg/jsk_travis/pull/55, but this assume you already install ansicolor plugin, i saw patched python-jenkins with install plugin feature but not remember which repository

**Comment by garaemon** [comment]
great!

My QoL is getting better.

![screenshot_from_2015-02-17 01 54 53](https://cloud.githubusercontent.com/assets/40454/6215871/ff552a56-b647-11e4-82fa-318970ee3a29.png)
