### ISSUE TITLE
Internal compiler error during cakin build

### ISSUE THREAD

**Issue by snozawa** [jsk-ros-pkg/jsk_travis#132]
Sometimes travis fails the following error:
```
g++: internal compiler error: Killed (program cc1plus)
```

If we build source several times like this:
`catkin build xxx || catkin build xxx`
, is this reduce the possibility of internal compile error?
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L154

**Comment by garaemon** [comment]
see https://github.com/travis-ci/travis-ci/issues/1972

**Comment by k-okada** [comment]
running catkin build twice works for this, but it also hide other problem
too.

--
◉ Kei Okada
