### ISSUE TITLE
Possible to change filename .rosinstall?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_travis#133]
.rosinstall is same name as the default config file for wstool command.
it causes problem sometime for me.

Is that possible to change the name?
maybe with config variable in `.travis.yml` in each repository.

**Comment by k-okada** [comment]
what kind of problem ?

**Comment by wkentaro** [comment]
wstool searches .rosinstall to root of filesystem.
so, when doing wstool info in the package which includes .rosinstall, the result is not under ros/indigo/src but ros/indigo/src/jsk_recognition.
and also, when doing wstool update (unexpectedly) in under package, it clones repository in the package. not under actual root (ros/indigo/src).

**Comment by k-okada** [comment]
that may big change, but I think it is acceptable, what is the candidate of
the fliename .rosinstall.yaml, .rosrepo.yaml?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
what the file for ?
only to test the package with unreleased version?

2015年9月2日水曜日、Kei Okada<notifications@github.com>さんは書きました:

> that may big change, but I think it is acceptable, what is the candidate of
> the fliename .rosinstall.yaml, .rosrepo.yaml?
>
> --
> ◉ Kei Okada
>
>
> On Tue, Sep 1, 2015 at 11:51 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > wstool searches .rosinstall to root of filesystem.
> > so, when doing wstool info in the package which includes .rosinstall, the
> > result is not under ros/indigo/src but ros/indigo/src/jsk_recognition.
> > and also, when doing wstool update (unexpectedly) in under package, it
> > clones repository in the package. not under actual root (ros/indigo/src).
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_travis/issues/133#issuecomment-136749736
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_travis/issues/133#issuecomment-136920419>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
Yes

**Comment by wkentaro** [comment]
why not .travis.rosinstall?

2015年9月2日水曜日、Kei Okada<notifications@github.com>さんは書きました:

> Yes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_travis/issues/133#issuecomment-136931817>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
.travis.repo
.travis.install
.travis.ros
.repo.yaml
.install
...



--
◉ Kei Okada

**Comment by wkentaro** [comment]
it seems that the name of .rosinstall will not be changed in at least a few years.
https://github.com/vcstools/wstool/issues/19

So I personally think .travis.rosinstall is one of the best.

**Comment by k-okada** [comment]
Lgtm
