### ISSUE TITLE
What is NO_SUDO for?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_travis#141]
There is NO_SUDO section,
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L27
but not in other lines...
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L66

**Comment by garaemon** [comment]
It expects USE_JENKINS=true

**Comment by wkentaro** [comment]
I see. thanks.
