### ISSUE TITLE
Do not run tests for other packages

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_travis#142]
`catkin run_tests [package]` run tests for all the (dependent) packages in workspace.
In order to disable test in them, need to use `catkin config --blacklist` or `catkin config --whitelist`

**Comment by wkentaro** [comment]
`--no-deps` does not work?
```
catkin run_tests [package] --start-with-this --no-deps
```

**Comment by garaemon** [comment]
`--start-with-this` works?

**Comment by garaemon** [comment]
`--no-deps` looks good

**Comment by wkentaro** [comment]
correctly,
```
catkin run_tests [package] [--start-with-this | --no-deps]
```
both --start-with-this and --no-deps does work for this issue.

**Comment by garaemon** [comment]
BTW, if `--no-deps` works well, we don't need `--start-with-this`?

**Comment by wkentaro** [comment]
Yeah, and using only --no-deps seems better.
