### ISSUE TITLE
Pretty output of test failure which is good for contributors to view

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_travis#159]
suggested at https://github.com/jsk-ros-pkg/jsk_recognition/pull/1192#issuecomment-145493665

- [x] Highlight test failed line (maybe after seeing exit code)
- [x] Summarize each package build (with `--summarize` option)

**Comment by wkentaro** [comment]
@k-okada 

>  Highlight test failed line (maybe after seeing exit code)

we should edit https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L32-L36 for this?

**Comment by k-okada** [comment]
i think this is already highlighted at
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L16

--
◉ Kei Okada

**Comment by wkentaro** [comment]
why no highlighted line here?

* https://github.com/jsk-ros-pkg/jsk_recognition/pull/999#partial-pull-merging
* https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/70068721

![image](https://cloud.githubusercontent.com/assets/4310419/10280604/3e4e75d4-6ba9-11e5-9415-48b2df19e0d0.png)

**Comment by wkentaro** [comment]
there is highlighted line when success.

![image](https://cloud.githubusercontent.com/assets/4310419/10280626/79d7cf06-6ba9-11e5-9c93-32ff23c55891.png)

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/10428555/493bdcc8-712d-11e5-8b5a-ed382dcd36dc.png)

Done.
