### ISSUE TITLE
Use apt-cacher-ng to cache apt-get packages

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_travis#201]
http://docs.docker.com/engine/examples/apt-cacher-ng/
http://qiita.com/hyotan/items/a17fa1bbb7c202590f70

It may skip downloading deb packages.

**Comment by garaemon** [comment]
@k-okada 

Could you run `sudo apt-get install apt-cacher-ng` on jenkins?

**Comment by wkentaro** [comment]
oh, really nice feature! :sparkles:

**Comment by k-okada** [comment]
done

--
◉ Kei Okada

**Comment by garaemon** [comment]
not installed yet
```
lueda@jenkins:~$ aptitude search apt-cacher-ng
p   apt-cacher-ng                                     - caching proxy server for software repositories             
p   apt-cacher-ng:i386                                - caching proxy server for software repositories             
```

**Comment by garaemon** [comment]
Enable apt-cacher-ng on docker clients:
https://github.com/jsk-ros-pkg/jsk_travis/pull/203

**Comment by k-okada** [comment]
oh, you mean jenkins, I installed in docker image,  fixed now.

--
◉ Kei Okada

**Comment by garaemon** [comment]
http://askubuntu.com/questions/119298/apt-get-using-apt-cacher-ng-fails-to-fetch-packages-with-hash-sum-mismatch

**Comment by garaemon** [comment]
not so fast
![screenshot from 2015-12-11 19 23 11](https://cloud.githubusercontent.com/assets/40454/11741490/c90611f6-a03c-11e5-80a1-846726bbf339.png)

**Comment by garaemon** [comment]
Still it takes 24 minutes to install apts

![screenshot from 2015-12-11 19 26 02](https://cloud.githubusercontent.com/assets/40454/11741558/2f0aaade-a03d-11e5-8a06-1c5c91364495.png)

**Comment by garaemon** [comment]
I found `pip install scikit-image` takes much time because it depends on numpy.

@wkentaro Do you know how to cache pip?

**Comment by garaemon** [comment]
http://stackoverflow.com/questions/4806448/how-do-i-install-from-a-local-cache-with-pip

**Comment by garaemon** [comment]
1. cache downloading of pip
2. use ccache to compile inside of `pip install`

**Comment by garaemon** [comment]
@wkentaro makaseta

**Comment by wkentaro** [comment]
> I found pip install scikit-image takes much time because it depends on numpy.

I think if numpy is installed beforehand by apt, pip does not install it via pip.

**Comment by wkentaro** [comment]
> use ccache to compile inside of pip install

I don't know if this is possible.

**Comment by garaemon** [comment]
> I think if numpy is installed beforehand by apt, pip does not install it via pip.

https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/96754580#L1603

**Comment by wkentaro** [comment]
I see, scikit-image depends on newer numpy. So it rebuilds it.

**Comment by wkentaro** [comment]
I think following PR fixes this issue:
- https://github.com/jsk-ros-pkg/jsk_travis/pull/209
- https://github.com/jsk-ros-pkg/jsk_travis/pull/208
