### ISSUE TITLE
Install scikit-image and dlib on docker image

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_travis#214]
@k-okada Could you install following pip packages on docker images?

* scikit-image
* dlib

jsk_recognition test wastes most of the time to install pip packages.

**Comment by k-okada** [comment]
done

--
◉ Kei Okada

**Comment by garaemon** [comment]
great.
now jsk_recognition/indigo tests end in 20 minutes.
https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/97165729

**Comment by garaemon** [comment]
hydro docker image is not updated yet.

http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_recognition-hydro-deb-false-true/248/console

**Comment by k-okada** [comment]
sorry for late, done

--
◉ Kei Okada
