### ISSUE TITLE
build non-apt dependencies

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_travis#233]
In case that test packages are depend on some packages which is not released on apt, how we should append and build them on test?

**Comment by wkentaro** [comment]
What is **test packages**?

**Comment by furushchev** [comment]
@wkentaro in jsk_roseus repository, they are `roseus`, `roseus_smach`, `roseus_mongo` and `roseus_tutorials`.
`roseus_tutorials` package depends on a not-yet-released-as-deb package.
I added it to `.travis.rosinstall`, but still it doesn't be built.
(In build process, build command is executed with `--no-dep`, so it is reasonable that dependencies are not built, but I'd like to build dependencies too.)

**Comment by furushchev** [comment]
O, I misunderstood, it was executed without `--no-dep`. Anyway it is weird not to be built dependencies.

**Comment by furushchev** [comment]
ok. if `USE_DEB` is not set `false`, no packages are downloaded.
I'm trying to add option `ROSINSTALL_FILES` to `jsk_travis` to install custom rosinstall files.

**Comment by wkentaro** [comment]
:+1:

**Comment by k-okada** [comment]
sorry I can not understand why just adding to '.travis.rosinstall' does not work? did you add them into `test_depend` in `package.xml` ?

**Comment by furushchev** [comment]
@k-okada Currently `.travis.rosinstall` in jsk-ros-pkg/jsk_roseus repo is used to test euslisp-release and jskeus-release with roseus. I think we cannot use `.travis.rosinstall` to fetch not-released packages as is done in other repos in this case.
The problem is `.travis.rosinstall` is merged to `.rosinstall` only when `USE_DEB=false`, not `USE_DEB=source`

**Comment by wkentaro** [comment]
`USE_DEB=true`
- `.travis.rosinstall`: not used
- `.travis.rosinstall.$ROS_DISTRO`: not used
- `setup-upstream.sh`: not used
- `$ROS_INSTALL_FILES` (default: `""`): *used*

`USE_DEB=false`
- `.travis.rosinstall`: used
- `.travis.rosinstall.$ROS_DISTRO`: used
- `setup-upstream.sh`: not used
- `$ROS_INSTALL_FILES` (default: `".travis.rosinstall .travis.rosinstall.$ROS_DISTRO"`): used

`USE_DEB=source`
- `.travis.rosinstall`: not used
- `.travis.rosinstall.$ROS_DISTRO`: not used
- `setup-upstream.sh`: used
- `$ROS_INSTALL_FILES` (default: `""`): used

**Comment by k-okada** [comment]
please ask for release

--
◉ Kei Okada

**Comment by furushchev** [comment]
opened issue
https://github.com/ros-interactive-manipulation/tabletop_object_perception/issues/1

**Comment by k-okada** [comment]
which program do you use in tabletop_object_perception ?

--
◉ Kei Okada

**Comment by k-okada** [comment]
if we can pass travis by  ROS_INSTALL_FILES, I'm afraid we'll have
trouble on bloom-release in the future.
--
◉ Kei Okada

**Comment by furushchev** [comment]
there is tabletop demo launch in roseus_tutorials.
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus_tutorials/launch/tabletop-object-detector.launch#L89

**Comment by k-okada** [comment]
I wonder if we can "easily" rewrite them with jsk_pcl_ros

--
◉ Kei Okada

**Comment by furushchev** [comment]
ok, I rewrote relatively easily
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/217
