### ISSUE TITLE
Request of next release: version 0.4.9

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_travis#274]
I need these:

![image](https://cloud.githubusercontent.com/assets/4310419/15627856/7c4b881c-252c-11e6-9254-5df20b5cc3d2.png)

**Comment by k-okada** [comment]
done
https://github.com/jsk-ros-pkg/jsk_travis/commit/c05f66377f0d1aa034b4368ded5704ff9a0a7869

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Thank you
