### ISSUE TITLE
Jenkins job hangs at `sudo docker ps -a`

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_travis#275]
<img width="822" alt="screen shot 2016-05-29 at 12 15 12" src="https://cloud.githubusercontent.com/assets/4310419/15631199/15a691b8-2597-11e6-989c-3173d2763389.png">

Related to https://github.com/docker/docker/issues/18013

**Comment by k-okada** [comment]
This is usually docker itself is hung, restart docked or restart server
machine

2016年5月29日日曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> [image: screen shot 2016-05-29 at 12 15 12]
> <https://cloud.githubusercontent.com/assets/4310419/15631199/15a691b8-2597-11e6-989c-3173d2763389.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_travis/issues/275>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3NgY9mvz-oKFWBk4XSdxzQe3FM_Lks5qGQTrgaJpZM4IpNA8>
> .
>


-- 
--
◉ Kei Okada
