### ISSUE TITLE
support more than 3 <numToKeep>3</numToKeep> value

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_travis#277]
currently jenkins keeps 3 last logs, so if you run more than 5 pull request, travis may not get result files and fails (just one hypthessis with @knorth55)
 https://github.com/jsk-ros-pkg/jsk_travis/commit/dfa2340bbba04f23fb835c3142a48023d465106d#diff-efc5ac811892f9de4e3c85726ea47d96R44
If this is correct, we need special option to increase numToKeep for super active repository like jsk_apc

**Comment by k-okada** [comment]
Cc: @wkentaro

**Comment by wkentaro** [comment]
> currently jenkins keeps 3 last logs, so if you run more than 5 pull request,

The number **3** means number of Travis jobs? or Travis builds?
Travis has more than 3 jobs in one job in jsk_recognition, so it should fail at all time.
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/.travis.yml#L19-L25

**Comment by k-okada** [comment]
it should be number of jenkins jobs,
and you're correct, I thought there is a case that jenkins passed the jobs
but travis did not get that result because the log of the jenkins jobs is
deleted before the travis fetch them, may be this was not happend

--
◉ Kei Okada
