### ISSUE TITLE
Why latest catkin is installed?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_travis#283]
It seems that @k-okada changed it.
https://github.com/jsk-ros-pkg/jsk_travis/blame/master/travis.sh#L104

Installing HEAD version of catkin causes problems because of some api changes like:

- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1784#issuecomment-233686059 
- https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/68
- https://github.com/jsk-ros-pkg/jsk_common/pull/1428

because of https://github.com/ros/catkin/pull/813 .

So I'm changing the `travis.sh` for installing `ros-${ROSDISTRO}-catkin` by apt.
Do you agree? @k-okada

**Comment by wkentaro** [comment]
cc @furushchev

**Comment by k-okada** [comment]
thanks, yes I agree, I just forget t revert this PR when
https://github.com/ros/catkin/pull/705 was merged and released
```
### https://github.com/ros/catkin/pull/705
[ ! -e /tmp/catkin ] && (cd /tmp/; git clone -q
https://github.com/ros/catkin)

```

--
◉ Kei Okada
