### ISSUE TITLE
0.4.19 Release request

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_travis#308]
There are important updates, I think.
- #307 
- #306 
- https://github.com/jsk-ros-pkg/jsk_travis/pull/300

**Comment by wkentaro** [comment]
but #300 has not yet been merged, is that ok for u?

**Comment by k-okada** [comment]
ok, released 0.4.19, https://github.com/jsk-ros-pkg/jsk_travis/commit/83c01f1c42a835a25a3b7d346b292714da401bcf

Please continu discussion on #300
