### ISSUE TITLE
jsk_travis version checking does not work on Jenkins maybe because of missing .git directory

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_travis#309]
Moved from https://github.com/jsk-ros-pkg/jsk_travis/pull/306#issuecomment-246687717

Code is here:
- https://github.com/jsk-ros-pkg/jsk_travis/blob/0.4.18/travis.sh#L46-L52 (0.4.18)
- https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L89-L104 (0.4.19)

**Comment by k-okada** [comment]
becase of old git binary on jenkins?
```
jenkins@jenkins:~/jobs/trusty-travis-jsk-ros-pkg-jsk-3rdparty-indigo-deb-true/workspace/jenkins-trusty-travis-jsk-ros-pkg-jsk-3rdparty-indigo-deb-true-11/jsk-ros-pkg/jsk_3rdparty$ cat .travis/.git 
gitdir: /var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk-3rdparty-indigo-deb-true/workspace/jenkins-trusty-travis-jsk-ros-pkg-jsk-3rdparty-indigo-deb-true-11/jsk-ros-pkg/jsk_3rdparty/.git/modules/.travis
```
```
k-okada@kokada-t440s:/tmp/jsk_3rdparty$ cat .travis/.git 
gitdir: ../.git/modules/.travis
```
updated and see what's happens
http://askubuntu.com/questions/449977/which-ppa-has-the-most-current-version-of-git-for-12-04-ppagit-core-ppa-is-out

**Comment by wkentaro** [comment]
Hmm, maybe checking the version only on Travis is better, don't you think?
Because all source files are firstly cloned into the travis.
