### ISSUE TITLE
release request

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_travis#318]
there are some update from latest release.

- add feature to test with gazebo
https://github.com/jsk-ros-pkg/jsk_travis/pull/316

- bugfix: suppress unnecessary output on docker
https://github.com/jsk-ros-pkg/jsk_travis/pull/312

- add watchdog for monitoring canceled travis jobs and sync to jenkins 
https://github.com/jsk-ros-pkg/jsk_travis/pull/317

**Comment by k-okada** [comment]
please fix existing problem /tmp/docker_ps_a.txt

--
◉ Kei Okada


2016-10-20 23:43 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by k-okada** [comment]
thank you, released -> https://github.com/jsk-ros-pkg/jsk_travis/commit/9100c3e65a4747cba6f98373f074341c342f6661

**Comment by furushchev** [comment]
@k-okada Thank you too! 👍
