### ISSUE TITLE
travis_jenkinsで環境変数を渡すか、それに類する方法

### ISSUE THREAD

**Issue by snozawa** [jsk-ros-pkg/jsk_travis#325]
travis_jenkinsでtravisからjenkinsに対して、
環境変数を渡すか、それに類する方法があるか質問させてもらいたく、issueきりまいした。

やりたいことは、rtmros_commonというjsk_travisを使ってるパッケージで、
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/CMakeLists.txt#L268
とtravisのテスト用の特定の環境変数がセットされたときだけ
テストがはしるようになってるのですが、こんなかんじのことがしたいです。

もともとこのrtmros_commonパッケージは公式にはeuslispに依存してないけど、
euslispのインターフェースもそなえててJSKの人はeuslispから使ってて、
travis上でもそれをテストしたいというものです。
なので、（なんらかの条件に合致する）全テストジョブでeuslispのテストが走るようにするというよりは、
特殊なフラグがたったらeuslispのテストがはしる、というようにしていました。
https://github.com/start-jsk/rtmros_common/blob/master/.travis.yml#L22

USE_JENKINSにする前はこれで動いてましたが、USE_JENKINSでは
どうやら環境変数がtravis -> jenkinsに渡ってないような気がしました。

環境変数をわたすようにするか、
それとも今よくよく考えたら
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/CMakeLists.txt#L268
の部分を修正して「JENKINSでかつEXTRA_DEBの設定のおかげでroseus_FOUNDな環境」という
IF文もかけそうなきがしてきましたが、
何かオススメの方法、類する方法はありますでしょうか。

ちなみに、JENKINSかどうかを判別する方法・環境変数は何がオススメでしょうか。
JENKINS_HOMEとか？

よろしくお願いします。

**Comment by wkentaro** [comment]
まず、環境変数はここで Travis -> Jenkinsに渡しています。
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis_jenkins.py#L119

つぎにJenkinsかどうかということを判別する方法は`TRAVIS_JOB_ID`がセットされているかどうかというのが良く使われています。
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L274

**Comment by snozawa** [comment]
ありがとうございます。

> まず、環境変数はここで Travis -> Jenkinsに渡しています。
> https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis_jenkins.py#L119

この部分は、user definedな任意の環境変数を渡す（今だとIS_EUSLISP_TRAVIS_TESTみたいな変数）
のは現状だと難しそうと理解してるのですが、あってますか？


> つぎに、Jenkinsかどうかということを判別する方法はTRAVIS_JOB_IDがセットされているかどうかというのが良く使われています。
> https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L274

これは、
「travis.shから実行されてTRAVIS_JOB_IDがない」　＝　「JENKINS」
と判定していることになりますか？
「TRAVIS_JOB_IDがない」をCMakeにかくんだと思いますが、そうすると
手元でcatkin buildしたときにもTRAVIS_JOB_IDがないので実行されたりしますか？
もしその場合、「travis.shから実行されたかどうか」を判断できる環境変数か、
「JENKINSをそのもの」を判断する環境変数があるとうれしいかもしれないです。

**Comment by k-okada** [comment]
IS_EUSLISP_TRAVIS_TEST を jsk_travis に書くのは今ひとつな気がします．
なので、euslispのテストはtravis上で動かすものにする．いまならinidgoに切り替える、
か、
euslispがインストールされている時だけ、テストをする、という風にかえるのがいいんじゃないでしょうか．

--
◉ Kei Okada


2017年3月9日 16:17 Kentaro Wada <notifications@github.com>:

**Comment by snozawa** [comment]
ありがとうございます。そうですね。

> euslispがインストールされている時だけ、テストをする、という風にかえるのがいいんじゃないでしょうか．

こちらが良いかと思いました。

**Comment by YutoUchimi** [comment]
@pazeshun Does #395 solve this issue?

**Comment by pazeshun** [comment]
@YutoUchimi Thank you for finding this issue!
Yes, #395 solves this issue.

> euslispがインストールされている時だけ、テストをする、という風にかえるのがいいんじゃないでしょうか．

Such solutions are preferred in most cases, rather than creating new environment variables.
However, sometimes we need #395 to reduce test time, because #395 enables to create variables used to switch tests in one package:
https://github.com/start-jsk/rtmros_common/commit/d354e5b2ddca9d2591908047fa5f850519469a5c
