### ISSUE TITLE
run_tests rather than test as a terget of catkin?

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_travis#4]
[The document](http://wiki.ros.org/rostest/Writing) says:
```
If you run make run_tests on the command line in the build folder now, the test binary will get compiled and the rostest file 'test/mytest.test' will be launched by rostest.
```

and `test` target does not build any executable listed by ADD_ROSTEST_GTEST macro.

**Comment by k-okada** [comment]
I'm asking question on the difference betwen run_test / test -> https://github.com/catkin/catkin_tools/issues/139
