### ISSUE TITLE
fatal: unsafe repository error occured

### ISSUE THREAD

**Issue by iory** [jsk-ros-pkg/jsk_travis#439]
Recent git changes cause error.
https://github.com/jsk-ros-pkg/jsk_3rdparty/runs/6072237599?check_suite_focus=true#step:5:511

This link seems to be helpful
https://github.com/actions/checkout/issues/760#issue-1202634949

**Comment by k-okada** [comment]
this happens before we checkout .travis directory, see https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/338

**Comment by iory** [comment]
Thank you!
