### ISSUE TITLE
Allow multiple jobs on one project in jenkins

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_travis#61]
Now jenkins looks it only runs one job per one project.
I'd like to run multiple testing per one project

**Comment by k-okada** [comment]
enabled concurrent build on http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-garaemon-jsk_recognition-indigo-deb-true-true/configure, for testing, if this project seems ok, then I'll enable this feature on the travis script

**Comment by k-okada** [comment]
above comment is not correct, that configuration will be overwritten travis scripts, so please check #63

**Comment by garaemon** [comment]
done
