### ISSUE TITLE
stable release

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_travis#80]
I have released new version of jsk_travis, please use https://github.com/jsk-ros-pkg/jsk_travis/commit/cebe407f5ded01f24ea0ba6ed4144b93774b8a8d

**Comment by garaemon** [comment]
We still have roslint problem. https://github.com/jsk-ros-pkg/jsk_demos/pull/276

**Comment by k-okada** [comment]
I think this is not geneus problem, I suspect this is because of existing old rosmake files, see what's happend in https://github.com/jsk-ros-pkg/jsk_demos/pull/280

**Comment by garaemon** [comment]
FYI, My local script to update .travis
```shell
#!/bin/bash
set -e
user_name=garaemon
repo=$(git remote show origin -n | grep 'Fetch URL' | cut -f5 -d" " \
    | xargs -n 1 -i basename {} .git)
echo adding git@github.com:${user_name}/${repo}.git as ${user_name}
git remote add ${user_name} git@github.com:${user_name}/${repo}.git && echo 0
git checkout -b update-travis-$(date +%Y-%m-%d)
cd .travis
git checkout master
git pull
cd ..
git add .travis
git commit -m "Update .travis"
git push garaemon update-travis-$(date +%Y-%m-%d)
hub pull-request -m "update .travis"
```

**Comment by k-okada** [comment]
closed, we're now releasing travis with version number
